[package]
name = "rimui"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = {version = "0.13.1", features = ["image"]}
iced_graphics = {version = "0.13.0",features = ["geometry"]}
iced_widget = {version = "0.13.4",features = ["image"]}
image = "0.25.6"
